
alycmsfeertgjmpqkwup
# This is the main configuration file for Supabase CLI.
# Please keep the line above so the IDE/linters recognize the format.

[functions.check-whatsapp-status]
verify_jwt = true

[functions.disconnect-whatsapp]
verify_jwt = true

[functions.generate-whatsapp-qr]
verify_jwt = true

[functions.get-whatsapp-chats]
verify_jwt = true

[functions.get-whatsapp-messages]
verify_jwt = true

[functions.connect-whatsapp-api]
verify_jwt = false

[functions.send-connection-notification]
verify_jwt = true
