// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://alycmsfeertgjmpqkwup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseWNtc2ZlZXJ0Z2ptcHFrd3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzQ3MTYsImV4cCI6MjA2MDgxMDcxNn0.0RpcXTHWwyo7ar-pY_F71em4a417wpxA4U8UXhrmlj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
